"""empty message

Revision ID: 3fa6b2aa8a10
Revises: 90121a489b9c
Create Date: 2019-05-13 00:52:38.248064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa6b2aa8a10'
down_revision = '90121a489b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'team_name')
    # ### end Alembic commands ###
