"""empty message

Revision ID: 90121a489b9c
Revises: 
Create Date: 2019-05-13 00:50:21.212613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90121a489b9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('team_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('terminiology', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatis')
    op.drop_table('team_admin')
    op.drop_table('team')
    # ### end Alembic commands ###
