#!/usr/bin/env python
import os
from gunicorn.app.base import BaseApplication
from gunicorn.six import iteritems
from whatis.config import DevelopmentConfig
from whatis.app import WhatisApp

os.environ['RUNTIME_CONTEXT'] = 'local'

class WhatisDeployer(BaseApplication):

    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super(WhatisDeployer, self).__init__()

    def load_config(self):
        config = dict([(key, value) for key, value in iteritems(self.options)
                       if key in self.cfg.settings and value is not None])
        for key, value in iteritems(config):
            self.cfg.set(key.lower(), value)

    def load(self):
        return self.application


WhatisDeployer(WhatisApp(config=DevelopmentConfig())).run()